version: "2"

services:
  redis:
    image: redis:latest
  web:
    build: .
    command: daphne multichat.asgi:application -b localhost -p 8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    links:
      - redis
