# Generated by Django 4.1.7 on 2023-02-17 15:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="chat",
            name="timestamp",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="message",
            name="msg_type",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "Message"),
                    (1, "Info"),
                    (2, "Status"),
                    (3, "Enter"),
                    (4, "Leave"),
                    (5, "Typing"),
                    (6, "Ping"),
                ],
                default=0,
            ),
        ),
    ]
